data: ${data}
model: ${model}
init:
    model: ${model}
    name: art.attacks.evasion.FastGradientMethod
    eps: .99
    batch_size : ${model.trainer.batch_size}
    targeted : false
    minimal : true
attack_size : 10
method : evasion
