vars:
  - conf/plots.yaml:line_plot
  - conf/plots.yaml:scatter_plot
  # - conf/plots.yaml:cat_plot
  - conf/clean.yaml:attacks
  - conf/clean.yaml:defences
  - conf/clean.yaml:params
  - conf/clean.yaml:fillna
stages:
  pre-commmit:
    cmd: pre-commit run --all-files  && chktex -q -V main.tex -n 24 -n 8 -n 1 # Suppresses warnings 8 (dash length), 24 (\labels inside floats), and 1 (trailing whitespace following a command)
    deps:
      - main.tex
      - sn-bibliography.bib
      - generate_plots/
      - plots/
  first_run:
    cmd: pdflatex  main.tex
    deps:
      - main.tex
    outs:
      - main.aux
      - main.log
      - main.out
      - main.ist
  big_run:
    cmd: pdflatex main.tex && bibtex main && pdflatex  main.tex && pdflatex  main.tex 
    deps:
      - main.tex
      - sn-bibliography.bib
      - plots/
      - main.aux
      - main.log
      - main.out
      - main.ist
    outs:
      - main.pdf
  arxiv: # Commented this out for now because /tmp doesn't have enough space to generate the plots on itchy and I don't need to run this anyway.
    cmd: >-
      rm -rf tmp/ && 
      python arxiv.py 
      --directories plots/combined plots
      --delete_these_dirs generate_plots/ tmp conf bst
      --extensions py yaml csv 
      --title "A Cost-Aware Approach to Adversarial Robustness in Neural Networks"
      --delete_these_files ".dvcignore" "main.aux" "main.blg" "main.out"  "main.pdf" "main.log"  "arxiv.log"
      --temporary_directory tmp
    deps:
      - arxiv.py
      - plots/
      - main.pdf
    outs:
      - "A Cost-Aware Approach to Adversarial Robustness in Neural Networks.zip"
      - arxiv.log
      - tmp/